# Generated by Django 5.0.1 on 2024-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
