# Generated by Django 5.0.1 on 2024-02-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_city_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='time',
        ),
    ]
